// Curated pool for the "comeback story" feature. Each entry is a real,
// verifiable comeback — a person, a company, or a historic event — with the
// exact Wikipedia page title to fetch a summary from.
//
// category is unused for now (single "comeback" bucket, per the current
// scope) but kept so a category filter can be added later without touching
// this list again.
export const STORY_SUBJECTS = [
  { id: "abraham-lincoln", title: "Abraham Lincoln", category: "person" },
  { id: "walt-disney", title: "Walt Disney", category: "company" },
  { id: "apple-1997", title: "Steve Jobs' return to Apple", category: "company" },
  { id: "nelson-mandela", title: "Nelson Mandela", category: "person" },
  { id: "j-k-rowling", title: "J. K. Rowling", category: "person" },
  { id: "oprah-winfrey", title: "Oprah Winfrey", category: "person" },
  { id: "michael-jordan", title: "Michael Jordan", category: "person" },
  { id: "dunkirk", title: "Dunkirk evacuation", category: "war" },
  { id: "battle-of-midway", title: "Battle of Midway", category: "war" },
  { id: "battle-of-stalingrad", title: "Battle of Stalingrad", category: "war" },
  { id: "marvel-bankruptcy", title: "Marvel Entertainment", category: "company" },
  { id: "lego-history", title: "The Lego Group", category: "company" },
  { id: "netflix-2011", title: "Netflix", category: "company" },
  { id: "old-spice", title: "Old Spice", category: "company" },
  { id: "colonel-sanders", title: "Colonel Sanders", category: "person" },
  { id: "vincent-van-gogh", title: "Vincent van Gogh", category: "person" },
  { id: "thomas-edison", title: "Thomas Edison", category: "person" },
  { id: "henry-ford", title: "Henry Ford", category: "person" },
  { id: "malala-yousafzai", title: "Malala Yousafzai", category: "person" },
  { id: "stephen-hawking", title: "Stephen Hawking", category: "person" },
  { id: "winston-churchill", title: "Winston Churchill", category: "person" },
  { id: "apollo-13", title: "Apollo 13", category: "event" },
  { id: "battle-of-britain", title: "Battle of Britain", category: "war" },
  { id: "steve-harvey", title: "Steve Harvey", category: "person" },
  { id: "howard-schultz", title: "Howard Schultz", category: "company" },
  { id: "starbucks-2008", title: "Starbucks", category: "company" },
  { id: "general-motors", title: "General Motors Chapter 11 reorganization", category: "company" },
  { id: "nintendo-history", title: "History of Nintendo", category: "company" },
  { id: "arnold-schwarzenegger", title: "Arnold Schwarzenegger", category: "person" },
  { id: "sylvester-stallone", title: "Sylvester Stallone", category: "person" },
  { id: "robert-downey-jr", title: "Robert Downey Jr.", category: "person" },
  { id: "abraham-lincoln-failures", title: "Electoral history of Abraham Lincoln", category: "person" },
  { id: "west-germany-wirtschaftswunder", title: "Wirtschaftswunder", category: "event" },
  { id: "japan-post-war", title: "Japanese post-war economic miracle", category: "event" },
  { id: "south-korea-economy", title: "Miracle on the Han River", category: "event" },
  { id: "rwanda-recovery", title: "Economy of Rwanda", category: "event" },
  { id: "chrysler-1979", title: "Chrysler bailout", category: "company" },
  { id: "ibm-1990s", title: "IBM", category: "company" },
  { id: "adobe-history", title: "Adobe Inc.", category: "company" },
  { id: "amazon-dotcom", title: "Dot-com bubble", category: "event" },
  { id: "muhammad-ali", title: "Muhammad Ali", category: "person" },
  { id: "andre-agassi", title: "Andre Agassi", category: "person" },
  { id: "michael-bloomberg", title: "Michael Bloomberg", category: "person" },
  { id: "walt-disney-company-1980s", title: "The Walt Disney Company", category: "company" },
  { id: "ford-motor-2006", title: "Ford Motor Company", category: "company" },
  { id: "hyundai-history", title: "Hyundai Motor Company", category: "company" },
  { id: "toyota-history", title: "Toyota", category: "company" },
  { id: "singapore-independence", title: "Economic history of Singapore", category: "event" },
  { id: "berlin-wall", title: "Fall of the Berlin Wall", category: "event" },
  { id: "nelson-mandela-robben-island", title: "Robben Island", category: "person" },
  { id: "demi-moore", title: "Demi Moore", category: "person" },
  { id: "keanu-reeves", title: "Keanu Reeves", category: "person" },
  { id: "steve-jobs-pixar", title: "Pixar", category: "company" },
];
